package com.nativelibs4java.directx.d3d10;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : d3d10.h:56</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("d3d10") 
public class D3D10_VIEWPORT extends StructObject {
	@Field(0) 
	public int TopLeftX() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public D3D10_VIEWPORT TopLeftX(int TopLeftX) {
		this.io.setIntField(this, 0, TopLeftX);
		return this;
	}
	@Field(1) 
	public int TopLeftY() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public D3D10_VIEWPORT TopLeftY(int TopLeftY) {
		this.io.setIntField(this, 1, TopLeftY);
		return this;
	}
	@Field(2) 
	public int Width() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public D3D10_VIEWPORT Width(int Width) {
		this.io.setIntField(this, 2, Width);
		return this;
	}
	@Field(3) 
	public int Height() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public D3D10_VIEWPORT Height(int Height) {
		this.io.setIntField(this, 3, Height);
		return this;
	}
	@Field(4) 
	public float MinDepth() {
		return this.io.getFloatField(this, 4);
	}
	@Field(4) 
	public D3D10_VIEWPORT MinDepth(float MinDepth) {
		this.io.setFloatField(this, 4, MinDepth);
		return this;
	}
	@Field(5) 
	public float MaxDepth() {
		return this.io.getFloatField(this, 5);
	}
	@Field(5) 
	public D3D10_VIEWPORT MaxDepth(float MaxDepth) {
		this.io.setFloatField(this, 5, MaxDepth);
		return this;
	}
}
