/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bridj_BridJ */

#ifndef _Included_org_bridj_BridJ
#define _Included_org_bridj_BridJ
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bridj_BridJ_exceptionsSupported
#define org_bridj_BridJ_exceptionsSupported 0L
#ifdef __cplusplus
}
#endif
#endif
