/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bridj_Platform_utsname */

#ifndef _Included_org_bridj_Platform_utsname
#define _Included_org_bridj_Platform_utsname
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
