package org.bridj.jawt;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : jawt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("jawt") 
class JAWT_DrawingSurfaceInfo extends StructObject {
	public JAWT_DrawingSurfaceInfo() {
		super();
	}
	public JAWT_DrawingSurfaceInfo(Pointer pointer) {
		super(pointer);
	}
	/**
	 * Pointer to the platform-specific information.  This can be safely<br>
	 * cast to a JAWT_Win32DrawingSurfaceInfo on Windows or a<br>
	 * JAWT_X11DrawingSurfaceInfo on Solaris.  See jawt_md.h for details.<br>
	 * C type : void*
	 */
	@Field(0) 
	public Pointer platformInfo() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * Pointer to the platform-specific information.  This can be safely<br>
	 * cast to a JAWT_Win32DrawingSurfaceInfo on Windows or a<br>
	 * JAWT_X11DrawingSurfaceInfo on Solaris.  See jawt_md.h for details.<br>
	 * C type : void*
	 */
	@Field(0) 
	public JAWT_DrawingSurfaceInfo platformInfo(Pointer platformInfo) {
		this.io.setPointerField(this, 0, platformInfo);
		return this;
	}
	/**
	 * Cached pointer to the underlying drawing surface<br>
	 * C type : jawt_DrawingSurface*
	 */
	@Field(1) 
	public Pointer ds() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * Cached pointer to the underlying drawing surface<br>
	 * C type : jawt_DrawingSurface*
	 */
	@Field(1) 
	public JAWT_DrawingSurfaceInfo ds(Pointer ds) {
		this.io.setPointerField(this, 1, ds);
		return this;
	}
	/**
	 * Bounding rectangle of the drawing surface<br>
	 * C type : JAWT_Rectangle
	 */
	@Field(2) 
	public org.bridj.jawt.JAWT_Rectangle bounds() {
		return this.io.getStructField(this, 2);
	}
	/**
	 * Bounding rectangle of the drawing surface<br>
	 * C type : JAWT_Rectangle
	 */
	@Field(2) 
	public JAWT_DrawingSurfaceInfo bounds(org.bridj.jawt.JAWT_Rectangle bounds) {
		this.io.setStructField(this, 2, bounds);
		return this;
	}
	/// Number of rectangles in the clip
	@Field(3) 
	public int clipSize() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * Clip rectangle array<br>
	 * C type : JAWT_Rectangle*
	 */
	@Field(4) 
	public org.bridj.jawt.JAWT_Rectangle clip() {
		return this.io.getStructField(this, 4);
	}
}
