package com.nativelibs4java.ffmpeg.avformat;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : libavformat/avformat.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avformat") 
public class AVMetadataTag extends StructObject {
	public AVMetadataTag() {
		super();
	}
	public AVMetadataTag(Pointer pointer) {
		super(pointer);
	}
	/// C type : char*
	@Field(0) 
	public Pointer<java.lang.Byte > key() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : char*
	@Field(0) 
	public AVMetadataTag key(Pointer<java.lang.Byte > key) {
		this.io.setPointerField(this, 0, key);
		return this;
	}
	/// C type : char*
	public final Pointer<java.lang.Byte > key_$eq(Pointer<java.lang.Byte > key) {
		key(key);
		return key;
	}
	/// C type : char*
	@Field(1) 
	public Pointer<java.lang.Byte > value() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : char*
	@Field(1) 
	public AVMetadataTag value(Pointer<java.lang.Byte > value) {
		this.io.setPointerField(this, 1, value);
		return this;
	}
	/// C type : char*
	public final Pointer<java.lang.Byte > value_$eq(Pointer<java.lang.Byte > value) {
		value(value);
		return value;
	}
}
