package com.nativelibs4java.ffmpeg.avdevice;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
import org.bridj.cpp.CPPRuntime;
/**
 * Wrapper for library <b>avdevice</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avdevice") 
@Runtime(CPPRuntime.class) 
public class AvdeviceLibrary {
	static {
		BridJ.register();
	}
	/// <i>native declaration : libavdevice/avdevice.h</i>
	public static final int LIBAVDEVICE_VERSION_MINOR = 2;
	/// <i>native declaration : libavdevice/avdevice.h</i>
	public static final int LIBAVDEVICE_VERSION_MICRO = 0;
	/// <i>native declaration : libavdevice/avdevice.h</i>
	public static final int LIBAVDEVICE_VERSION_MAJOR = 52;
	public native static void avdevice_version();
	public native static Pointer<java.lang.Byte > avdevice_configuration();
	public native static Pointer<java.lang.Byte > avdevice_license();
	public native static void avdevice_register_all();
}
