#!/bin/bash
#
# http://code.google.com/p/support/wiki/ScriptedUploads
#
# http://code.google.com/p/nativelibs4java/source/browse/trunk/libraries/jnaerator/CHANGELOG
#
BRIDJ_VERSION=0.6.2
JNAERATOR_VERSION=0.11
JAVACL_VERSION=1.0.0-RC3

USER=$1
PASSWORD=$2

# Modified script to add full description:
# wget http://support.googlecode.com/svn/trunk/scripts/googlecode_upload.py

function upload_artifact() {
    DIR_NAME="$1"
    PROJECT="$2"
    NAME="$3"
    VERSION="$4"
    CLASSIFIER="$5"
    SUMMARY="$6"
    
    
    DESCRIPTION="`cat ${PROJECT}_SUMMARY`

For more details, see https://github.com/ochafik/nativelibs4java/blob/master/libraries/$DIR_NAME/CHANGELOG"
    
    if [[ -z "$CLASSIFIER" ]]; then
        CLASSIFIER_SUFFIX=""
    else
        CLASSIFIER_SUFFIX="-$CLASSIFIER"
    fi

    FILE="$HOME/.m2/repository/com/nativelibs4java/$NAME/$VERSION/$NAME-$VERSION$CLASSIFIER_SUFFIX.jar"
    
    if [[ ! -f "${PROJECT}_SUMMARY" ]]; then
        echo "Failed to read ${PROJECT}_SUMMARY"
        exit 1
    fi
    if [[ ! -f "$FILE" ]]; then
        echo "Failed to read $FILE"
        exit 1
    fi
    

    $(dirname $0)/googlecode_upload.py -u "$USER" -w "$PASSWORD" -l Featured -s "$SUMMARY" -d "$DESCRIPTION" -p $PROJECT "$FILE" || ( echo "Upload failed" ; exit 1 )
}

  	 
upload_artifact jnaerator jnaerator jnaerator $JNAERATOR_VERSION shaded "JNAerator $JNAERATOR_VERSION"

for CLASSIFIER in "" "unix-only" "linux-only" "windows-only" "c-only" "android"; do
    if [[ -z "$CLASSIFIER" ]]; then
        SUMMARY_SUFFIX=""
    else
        SUMMARY_SUFFIX=" (`echo "$CLASSIFIER" | tr - " "`)"
    fi
    upload_artifact BridJ bridj bridj $BRIDJ_VERSION "$CLASSIFIER" "BridJ $BRIDJ_VERSION$SUMMARY_SUFFIX"
done

upload_artifact OpenCL javacl javacl $JAVACL_VERSION shaded "JavaCL $JAVACL_VERSION"
upload_artifact OpenCL javacl javacl-jna $JAVACL_VERSION shaded "JavaCL $JAVACL_VERSION (JNA version)"
upload_artifact OpenCL javacl javacl-demos $JAVACL_VERSION shaded "JavaCL Demos $JAVACL_VERSION"
upload_artifact OpenCL javacl javacl-interactive-image-demo $JAVACL_VERSION shaded "JavaCL Interactive Image Demo $JAVACL_VERSION"

