package lua;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : luaconf.h:558</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("lua") 
public class luai_Cast extends StructObject {
	public luai_Cast() {
		super();
	}
	@Field(0) 
	public double l_d() {
		return this.io.getDoubleField(this, 0);
	}
	@Field(0) 
	public luai_Cast l_d(double l_d) {
		this.io.setDoubleField(this, 0, l_d);
		return this;
	}
	@CLong 
	@Field(1) 
	public long l_l() {
		return this.io.getCLongField(this, 1);
	}
	@CLong 
	@Field(1) 
	public luai_Cast l_l(long l_l) {
		this.io.setCLongField(this, 1, l_l);
		return this;
	}
}
