/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nativelibs4java_runtime_DynCall */

#ifndef _Included_com_nativelibs4java_runtime_DynCall
#define _Included_com_nativelibs4java_runtime_DynCall
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
