/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nativelibs4java_runtime_Pointer */

#ifndef _Included_com_nativelibs4java_runtime_Pointer
#define _Included_com_nativelibs4java_runtime_Pointer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nativelibs4java_runtime_Pointer_LITTLE_ENDIAN
#define com_nativelibs4java_runtime_Pointer_LITTLE_ENDIAN 108L
#undef com_nativelibs4java_runtime_Pointer_BIG_ENDIAN
#define com_nativelibs4java_runtime_Pointer_BIG_ENDIAN 98L
/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    getSizeT
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_getSizeT
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    setSizeT
 * Signature: (JJ)Lcom/nativelibs4java/runtime/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_nativelibs4java_runtime_Pointer_setSizeT
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    getIntegerArrayElements
 * Signature: ([IJ)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_getIntegerArrayElements
  (JNIEnv *, jclass, jintArray, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    releaseIntegerArrayElements
 * Signature: ([IJI)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_releaseIntegerArrayElements
  (JNIEnv *, jclass, jintArray, jlong, jint);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_int
 * Signature: (JB)I
 */
JNIEXPORT jint JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1int
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_int
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1int
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_int_array
 * Signature: (JIB)[I
 */
JNIEXPORT jintArray JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1int_1array
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_int_array
 * Signature: (J[IIIB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1int_1array
  (JNIEnv *, jclass, jlong, jintArray, jint, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    getLongArrayElements
 * Signature: ([JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_getLongArrayElements
  (JNIEnv *, jclass, jlongArray, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    releaseLongArrayElements
 * Signature: ([JJI)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_releaseLongArrayElements
  (JNIEnv *, jclass, jlongArray, jlong, jint);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_long
 * Signature: (JB)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1long
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_long
 * Signature: (JJB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1long
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_long_array
 * Signature: (JIB)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1long_1array
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_long_array
 * Signature: (J[JIIB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1long_1array
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    getShortArrayElements
 * Signature: ([SJ)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_getShortArrayElements
  (JNIEnv *, jclass, jshortArray, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    releaseShortArrayElements
 * Signature: ([SJI)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_releaseShortArrayElements
  (JNIEnv *, jclass, jshortArray, jlong, jint);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_short
 * Signature: (JB)S
 */
JNIEXPORT jshort JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1short
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_short
 * Signature: (JSB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1short
  (JNIEnv *, jclass, jlong, jshort, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_short_array
 * Signature: (JIB)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1short_1array
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_short_array
 * Signature: (J[SIIB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1short_1array
  (JNIEnv *, jclass, jlong, jshortArray, jint, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    getByteArrayElements
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_getByteArrayElements
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    releaseByteArrayElements
 * Signature: ([BJI)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_releaseByteArrayElements
  (JNIEnv *, jclass, jbyteArray, jlong, jint);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_byte
 * Signature: (JB)B
 */
JNIEXPORT jbyte JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1byte
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_byte
 * Signature: (JBB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1byte
  (JNIEnv *, jclass, jlong, jbyte, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_byte_array
 * Signature: (JIB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1byte_1array
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_byte_array
 * Signature: (J[BIIB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1byte_1array
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    getCharacterArrayElements
 * Signature: ([CJ)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_getCharacterArrayElements
  (JNIEnv *, jclass, jcharArray, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    releaseCharacterArrayElements
 * Signature: ([CJI)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_releaseCharacterArrayElements
  (JNIEnv *, jclass, jcharArray, jlong, jint);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_char
 * Signature: (JB)C
 */
JNIEXPORT jchar JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1char
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_char
 * Signature: (JCB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1char
  (JNIEnv *, jclass, jlong, jchar, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_char_array
 * Signature: (JIB)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1char_1array
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_char_array
 * Signature: (J[CIIB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1char_1array
  (JNIEnv *, jclass, jlong, jcharArray, jint, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    getFloatArrayElements
 * Signature: ([FJ)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_getFloatArrayElements
  (JNIEnv *, jclass, jfloatArray, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    releaseFloatArrayElements
 * Signature: ([FJI)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_releaseFloatArrayElements
  (JNIEnv *, jclass, jfloatArray, jlong, jint);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_float
 * Signature: (JB)F
 */
JNIEXPORT jfloat JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1float
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_float
 * Signature: (JFB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1float
  (JNIEnv *, jclass, jlong, jfloat, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_float_array
 * Signature: (JIB)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1float_1array
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_float_array
 * Signature: (J[FIIB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1float_1array
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    getDoubleArrayElements
 * Signature: ([DJ)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_getDoubleArrayElements
  (JNIEnv *, jclass, jdoubleArray, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    releaseDoubleArrayElements
 * Signature: ([DJI)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_releaseDoubleArrayElements
  (JNIEnv *, jclass, jdoubleArray, jlong, jint);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_double
 * Signature: (JB)D
 */
JNIEXPORT jdouble JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1double
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_double
 * Signature: (JDB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1double
  (JNIEnv *, jclass, jlong, jdouble, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    get_double_array
 * Signature: (JIB)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_nativelibs4java_runtime_Pointer_get_1double_1array
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    set_double_array
 * Signature: (J[DIIB)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_set_1double_1array
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint, jbyte);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    malloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_malloc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    strlen
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_strlen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    wcslen
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_wcslen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    memcpy
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_memcpy
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    wmemcpy
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_wmemcpy
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    memmove
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_memmove
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    wmemmove
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_wmemmove
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    memchr
 * Signature: (JBJ)J
 */
JNIEXPORT jlong JNICALL Java_com_nativelibs4java_runtime_Pointer_memchr
  (JNIEnv *, jclass, jlong, jbyte, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    memcmp
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_nativelibs4java_runtime_Pointer_memcmp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_nativelibs4java_runtime_Pointer
 * Method:    memset
 * Signature: (JBJ)V
 */
JNIEXPORT void JNICALL Java_com_nativelibs4java_runtime_Pointer_memset
  (JNIEnv *, jclass, jlong, jbyte, jlong);

#ifdef __cplusplus
}
#endif
#endif
