/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bridj_Pointer */

#ifndef _Included_com_bridj_Pointer
#define _Included_com_bridj_Pointer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_bridj_Pointer_LITTLE_ENDIAN
#define com_bridj_Pointer_LITTLE_ENDIAN 108L
#undef com_bridj_Pointer_BIG_ENDIAN
#define com_bridj_Pointer_BIG_ENDIAN 98L
#undef com_bridj_Pointer_TYPE_FROM_DIRECT_BUFFER
#define com_bridj_Pointer_TYPE_FROM_DIRECT_BUFFER 0L
#undef com_bridj_Pointer_TYPE_FROM_INDIRECT_BUFFER
#define com_bridj_Pointer_TYPE_FROM_INDIRECT_BUFFER 1L
#undef com_bridj_Pointer_TYPE_FROM_RAW_ADDRESS
#define com_bridj_Pointer_TYPE_FROM_RAW_ADDRESS 2L
#undef com_bridj_Pointer_TYPE_FROM_ALLOCATED_ADDRESS
#define com_bridj_Pointer_TYPE_FROM_ALLOCATED_ADDRESS 3L
#undef com_bridj_Pointer_TYPE_FROM_POINTER_GET_POINTER_VALUE
#define com_bridj_Pointer_TYPE_FROM_POINTER_GET_POINTER_VALUE 4L
#ifdef __cplusplus
}
#endif
#endif
