#!/bin/bash

NL4J_HOME=/Users/ochafik/github/nativelibs4java2/libraries

rm -fR lib
mkdir lib

cp $NL4J_HOME/OpenCL/JavaCL/target/javacl-1.0-SNAPSHOT-shaded.jar lib

#cp $NL4J_HOME/BridJ/target/bridj-0.6.2-SNAPSHOT.jar lib
#cp $NL4J_HOME/OpenCL/JavaCL/target/javacl-1.0-SNAPSHOT.jar lib
#cp $NL4J_HOME/OpenCL/Core/target/javacl-core-1.0-SNAPSHOT.jar lib
#cp $NL4J_HOME/OpenCL/OpenCL4Java/target/opencl4java-1.0-SNAPSHOT.jar lib
