#!/bin/bash

OUT_FILE=out.txt

rm "$OUT_FILE"

LOOPS=10

DISABLE_SCALACL_PLUGIN=1 mvn clean scala:compile || exit 1
for (( c = 1; c <= $LOOPS; c++ )) ; do
	echo "Run $c / $LOOPS without ScalaCL's optimizing plugin" 
	scala -cp target/classes Test Normal >> "$OUT_FILE" ;
done

mvn clean scala:compile || exit 1
for (( c = 1; c <= $LOOPS; c++ )) ; do
	echo "Run $c / $LOOPS with ScalaCL's optimizing plugin" 
	scala -cp target/classes Test Optimized >> "$OUT_FILE" ;
done

