#!/bin/bash

CLASSES="
org.bridj.JNI
org.bridj.BridJ
org.bridj.Pointer
org.bridj.Platform
org.bridj.objc.ObjCJNI
"

if [[ "$@" != "clean" && "$@" != "fast" ]] ; then
	# Generate native sources from Velocity templates
	#mvn generate-sources -o
	#mvn compile -o
	
	# Generate JNI headers
	javah -d src/main/cpp/bridj -classpath target/classes $CLASSES ;
fi


if [[ -z "$TARGETS" ]] ; then
	if [[ -d /Applications ]] ; then
		TARGETS="default ios android" ;
	else
		TARGETS="default" ;
	fi ;
fi

cd src/main/cpp/bridj

for TARGET in $TARGETS ; do
	if [[ "$DEBUG" == "1" ]] ; then
		BUILD_CONFIG=debug ./Make.sh $@ || exit 1 ;
	else 
		if [[ "$@" == "fast" ]] ; then
			./Make.sh || exit 1 ;
		else
			./Make.sh $@ || exit 1 ;
		fi ;
	fi ;
done

