#!/bin/bash

if [[ ! -d dyncall ]]
then
	admin/checkout_and_patch_dyncall.sh dyncall src/main/cpp/bridj/dyncall.diff || ( echo "Failed to checkout and patch dyncall" && exit 1 )
fi

if [[ -z "$TARGETS" ]] ; then
	if [[ -d /Applications ]] ; then
		TARGETS="default ios android" ;
	else
		TARGETS="default" ;
	fi ;
fi

cd src/main/cpp/bridj

for TARGET in $TARGETS ; do
	if [[ "$DEBUG" == "1" ]] ; then
		TARGET=$TARGET BUILD_CONFIG=debug ./Make.sh $@ || exit 1 ;
	else 
		if [[ "$@" == "fast" ]] ; then
			TARGET=$TARGET ./Make.sh || exit 1 ;
		else
			TARGET=$TARGET ./Make.sh $@ || exit 1 ;
		fi ;
	fi ;
done

