package com.nativelibs4java.mono.bridj;
import com.nativelibs4java.mono.bridj.MonoLibrary.MonoDebugDataTable;
import com.nativelibs4java.mono.bridj.MonoLibrary.MonoImage;
import com.nativelibs4java.mono.bridj.MonoLibrary.MonoSymbolFile;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : /Library/Frameworks/Mono.framework/Headers/mono-2.0/mono/metadata/mono-debug.h:69</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mono") 
public class MonoDebugHandle extends StructObject {
	public MonoDebugHandle() {
		super();
	}
	public MonoDebugHandle(Pointer pointer) {
		super(pointer);
	}
	@Field(0) 
	public int index() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public MonoDebugHandle index(int index) {
		this.io.setIntField(this, 0, index);
		return this;
	}
	/// C type : char*
	@Field(1) 
	public Pointer<Byte > image_file() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : char*
	@Field(1) 
	public MonoDebugHandle image_file(Pointer<Byte > image_file) {
		this.io.setPointerField(this, 1, image_file);
		return this;
	}
	/// C type : MonoImage*
	@Field(2) 
	public Pointer<MonoImage > image() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : MonoImage*
	@Field(2) 
	public MonoDebugHandle image(Pointer<MonoImage > image) {
		this.io.setPointerField(this, 2, image);
		return this;
	}
	/// C type : MonoDebugDataTable*
	@Field(3) 
	public Pointer<MonoDebugDataTable > type_table() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : MonoDebugDataTable*
	@Field(3) 
	public MonoDebugHandle type_table(Pointer<MonoDebugDataTable > type_table) {
		this.io.setPointerField(this, 3, type_table);
		return this;
	}
	/// C type : MonoSymbolFile*
	@Field(4) 
	public Pointer<MonoSymbolFile > symfile() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : MonoSymbolFile*
	@Field(4) 
	public MonoDebugHandle symfile(Pointer<MonoSymbolFile > symfile) {
		this.io.setPointerField(this, 4, symfile);
		return this;
	}
}
