package com.nativelibs4java.mono.bridj;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : mono/metadata/debug-mono-symfile.h:43</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mono") 
public class MonoSymbolFileSourceEntry extends StructObject {
	public MonoSymbolFileSourceEntry() {
		super();
	}
	public MonoSymbolFileSourceEntry(Pointer pointer) {
		super(pointer);
	}
	@Field(0) 
	public int _index() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public MonoSymbolFileSourceEntry _index(int _index) {
		this.io.setIntField(this, 0, _index);
		return this;
	}
	@Field(1) 
	public int _data_offset() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public MonoSymbolFileSourceEntry _data_offset(int _data_offset) {
		this.io.setIntField(this, 1, _data_offset);
		return this;
	}
}
