#!/bin/bash
MVN_VERSION="`cat pom.xml | grep '<version' | head -n 1 | sed -e 's/.*<version>\(.*\)<\/version>.*/\1/g'`"
SBAZ_VERSION_AUTO="`echo $MVN_VERSION | sed -e "s/-SNAPSHOT/-SNAPSHOT-\`date '+%Y%m%d'\`/g"`"
SBAZ_VERSION=${SBAZ_VERSION:-$SBAZ_VERSION_AUTO}
LINK_BASE="http://nativelibs4java.sourceforge.net/sbaz/scalacl/"
#LINK_BASE="http://ochafik.com/sbaz/scalacl/"

SCALACL_HOME="`pwd`"

echo "###################################################"
echo "# ScalaCL : "
echo "#     Maven version = $MVN_VERSION"
echo "#      sbaz version = $SBAZ_VERSION"
echo "###################################################"

echo "# Building ScalaCL Collections"
mvn -Djarsigner.skip=false -Dstorepass=$KEYSTORE_PASS package -DskipTests                    

cd ../Plugin
echo "# Building ScalaCL Compiler Plugin"
mvn -Djarsigner.skip=false -Dstorepass=$KEYSTORE_PASS package -DskipTests
cd $SCALACL_HOME


TEMP_OUT=target/sbaz_out
LIB_JAR_OUT=$TEMP_OUT/lib
PLUGIN_JAR_OUT=$TEMP_OUT/misc/scala-devel/plugins

rm -fR $TEMP_OUT

mkdir -p $LIB_JAR_OUT
mkdir -p $PLUGIN_JAR_OUT

echo "# Copying libraries"
if [[ "$DONT_USE_SHADED" == "1" ]] ; then
	export SBAZ_VERSION="$SBAZ_VERSION-devel"
	NL4J_BASE="/Users/ochafik/.m2/repository/com/nativelibs4java"
	cp target/scalacl-$MVN_VERSION.jar $LIB_JAR_OUT
	cp $NL4J_BASE/bridj/0.5/bridj-5.jar $LIB_JAR_OUT
	cp $NL4J_BASE/opencl4java-bridj/1.0.0-RC1/opencl4java-bridj-1.0.0-RC1.jar $LIB_JAR_OUT
	cp $NL4J_BASE/javacl-core-bridj/1.0.0-RC1/javacl-core-bridj-1.0.0-RC1.jar $LIB_JAR_OUT
	cp $NL4J_BASE/javacl-bridj/1.0.0-RC1/javacl-bridj-1.0.0-RC1.jar $LIB_JAR_OUT
	cp $NL4J_BASE/libcl-bridj/1.0.0-RC1/libcl-bridj-1.0.0-RC1.jar $LIB_JAR_OUT ;
else
	cp target/scalacl-$MVN_VERSION-shaded.jar $LIB_JAR_OUT ;
fi

echo "# Copied the following libraries :"
ls -l $LIB_JAR_OUT

echo "# Copying compiler plugin libraries"
cp ../Plugin/target/scalacl-compiler-plugin-$MVN_VERSION.jar $PLUGIN_JAR_OUT

echo "# Packing for sbaz"
sbaz pack scalacl $TEMP_OUT \
	--linkbase $LINK_BASE \
	--version $SBAZ_VERSION \
	--outdir src/main/sbaz \
	--descfile ABOUT || ( echo "sbaz pack failed" && exit 1 )

mkdir -p src/main/sbaz

sbaz remove scalacl
sbaz compact
#sbaz retract scalacl/$SBAZ_VERSION
if [[ "$DONT_SHARE" == "1" ]] ; then
	echo "Not sharing the package (use SHARE=1 to share)"
	echo src/main/sbaz/scalacl-$SBAZ_VERSION.sbp ;
else 
	sbaz share *.advert ;
fi
mv *.advert src/main/sbaz
open src/main/sbaz

echo "Now please copy 'src/main/sbaz/scalacl-$SBAZ_VERSION.sbp' to '$LINK_BASE'"
